keys:
  - &hosts:
    - &desktop age12uj5thzwjff33t47jcwhx8ceekamexh3afuq5vyry0yu37sqy5fsztfd3r
  - &users:
    - &daniel age1fzr8qzwvl2rffdnc332g843gwn7f0eqcs39tlasmeyx95uhf2gsquua3hr
creation_rules:
  - path_regex: users/daniel/[^/]+\.yaml$
    key_groups:
    - age:
      - *desktop
      - *daniel
