# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=root"
        "compress=zstd:1"
        "noatime"
      ];
    };

  fileSystems."/home" =
    {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=home"
        "compress=zstd:1"
        "noatime"
      ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/mapper/root";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "compress=zstd:1"
        "noatime"
      ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/B908-4260";
      fsType = "vfat";
      options = [ "umask=0077" ];
    };

  boot.initrd.luks.devices.root = {
    device = "/dev/disk/by-uuid/f966830d-ab2f-432c-92ff-fd09831e9ed5";

    allowDiscards = true;
    bypassWorkqueues = true;
    crypttabExtraOpts = [ "tpm2-device=auto" "tpm2-measure-pcr=yes" ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
